/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.crud;
import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class PainelLinha extends javax.swing.JPanel {

    private Pessoa pessoa;
    private Conexao conexao;
    /**
     * Creates new form PainelLinha
     */
    public PainelLinha() {
        initComponents();
    }

    public PainelLinha(Pessoa pessoa, Conexao conexao) {
        initComponents();
        
        this.pessoa = pessoa;
        this.conexao = conexao;
        
        labelId.setText(Integer.toString(pessoa.getId()));
        labelNome.setText(pessoa.getNome());
        
        if (pessoa.getImagem() != null){
            labelFoto.setText("TEM FOTO");
        } else {
            labelFoto.setText("SEM FOTO");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        BtnExcluir = new javax.swing.JButton();
        BtnAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdicionarImg = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(200, 30));
        setMinimumSize(new java.awt.Dimension(200, 30));

        labelId.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelId.setText("id");

        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnAtualizar.setText("ATUALIZAR");
        BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nome:");

        AdicionarImg.setText("ADICIONAR IMG");
        AdicionarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarImgActionPerformed(evt);
            }
        });

        labelFoto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelFoto.setText("TEM FOTO");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNome.setText("NOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelId)
                .addGap(18, 18, 18)
                .addComponent(BtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdicionarImg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelId)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnAtualizar)
                    .addComponent(AdicionarImg))
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
            try {
                int id = pessoa.getId();
                Boolean ret = conexao.excluir(id);
            if (ret) {
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O identificador digitado não é um número");
        }    
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarActionPerformed
        Atualizar att = new Atualizar(pessoa, conexao);
        att.setVisible(true);
    }//GEN-LAST:event_BtnAtualizarActionPerformed

    private void AdicionarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarImgActionPerformed
        AdicionarImagem add = new AdicionarImagem(pessoa, conexao);
        add.setVisible(true);
    }//GEN-LAST:event_AdicionarImgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarImg;
    private javax.swing.JButton BtnAtualizar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
